name: off-explore
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pandas~=1.3.4
  - jupyterlab
  - matplotlib~=3.5.0
  - opentsne~=0.6.1
  - pynndescent~=0.5.5
  - scikit-learn~=1.0.1
  - seaborn[statsmodels,fastcluster]~=0.11.2
  - tabulate~=0.8.9
  - pip
  - pip:
      - black~=21.11.b1
