name: off-explore
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - jupyter
  - pandas=0.25.3
  - matplotlib=3.1.2
  - pynndescent=0.4.4
  - opentsne=0.3.12
  - seaborn
  - altair=4.0.0
